// Code generated by go-bindata. DO NOT EDIT.
// sources:
// tmpl/get_title_and_url.js.tmpl (937B)
// tmpl/support_sites.json.tmpl (740B)

package template

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data, name string) ([]byte, error) {
	gz, err := gzip.NewReader(strings.NewReader(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	clErr := gz.Close()
	if clErr != nil {
		return nil, clErr
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _tmplGet_title_and_urlJsTmpl = "\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xc4\x92\x4d\x6b\xdb\x4c\x10\xc7\xef\xfa\x14\xf3\xf0\x1c\x56\x22\xad\x9c\x73\x21\x85\x26\x98\x42\xa1\xb4\xe0\xd2\x50\x5c\x23\x46\xd2\x38\x5e\x2a\xed\x2c\x33\xb3\x12\x21\xf8\xbb\x17\x39\x4e\x5d\xbf\x1c\x0a\x3d\xf4\x36\xd2\x0c\xbf\xff\x8b\xf4\xff\x7f\xb3\xa4\x32\xab\x7d\x98\xb1\xa2\x36\xe2\xa3\xc1\xeb\x0e\x3e\xe0\x80\x8b\xdd\x53\x96\x35\x1c\xd4\x60\x2d\x1c\xac\x67\xb5\x0a\x63\xac\x02\xf6\x04\x37\xf0\x2e\xc6\xce\x37\x68\x9e\x43\xee\x16\x8f\x6a\xd4\xc3\x7c\xa0\x60\xea\x8a\x12\x0f\xcb\xcf\xc2\x0d\xa9\x92\x96\xe3\x86\x84\xf2\xa7\x03\xee\x0d\x98\x24\x82\x6d\x51\x4e\xcc\xbc\x58\x5e\xaf\x2e\x29\x9e\x88\x9d\xbb\x29\x5e\x8c\x36\x1b\xe1\xde\xa7\xbe\x1a\x50\x3c\x06\x53\xb8\x81\xa5\x7b\xcf\xfc\xd0\x11\xdc\x4d\x4b\x72\xaf\xc0\xdd\xed\xcf\xa6\xf9\x53\x24\xc1\x69\xf8\xea\x07\xec\x5a\x3f\x8d\xb7\x82\x03\xc1\xad\xf0\xa8\x24\xd3\x8b\x8f\xbe\x11\x56\x5e\x1b\xcc\xdb\x07\x72\x2f\x2e\x47\xaa\x7f\x78\x3b\x16\x5b\xe0\x1a\x65\x47\xb9\xdf\x6d\xdd\x2a\xcb\xfc\x1a\xf2\x33\x6b\xa5\x72\x4f\xf9\xa1\xd0\xb7\x17\x6a\x2e\xd5\x50\x4c\xef\xbd\x6d\x7e\x5d\x16\x45\x01\x4f\x19\x00\xc0\x80\x02\x4d\x12\xa1\x60\x95\x61\x5d\x99\xb7\x6e\xfa\x32\x47\x9c\x72\xf4\xa1\xe5\x51\x97\xd7\xab\x12\x1b\xf3\x03\x7d\xc1\x7a\xdf\xf7\x45\x4a\x92\xee\xcf\x18\x49\xba\xbc\xc8\xb6\x40\x9d\x12\x4c\x11\x4f\xea\xf8\x07\x01\xf7\xc7\x7f\x97\xf0\x37\xc8\x51\xc4\x67\x4f\xb6\x11\x1e\x21\xd0\x08\x73\x11\x96\xdc\x7d\xe3\x04\x81\xa8\x05\x04\x4d\x31\xb2\x18\xb5\x50\x3f\xff\x3b\x80\x0a\x8f\x9c\xe4\x20\x06\x18\xa3\x2b\xb2\x6d\x96\x9d\x3a\xba\x02\xf7\x3d\x38\xb8\x3a\x4f\xfc\x33\x00\x00\xff\xff\x85\x1c\x14\x03\xa9\x03\x00\x00"

func tmplGet_title_and_urlJsTmplBytes() ([]byte, error) {
	return bindataRead(
		_tmplGet_title_and_urlJsTmpl,
		"tmpl/get_title_and_url.js.tmpl",
	)
}

func tmplGet_title_and_urlJsTmpl() (*asset, error) {
	bytes, err := tmplGet_title_and_urlJsTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "tmpl/get_title_and_url.js.tmpl", size: 937, mode: os.FileMode(0644), modTime: time.Unix(1693622967, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xe7, 0x7b, 0x8c, 0x7f, 0x82, 0x2f, 0x63, 0x30, 0x77, 0x70, 0xc8, 0x49, 0x76, 0xe2, 0x29, 0x28, 0x2f, 0x26, 0x69, 0x6b, 0xe8, 0x31, 0xaa, 0x2b, 0x4c, 0xe8, 0x16, 0xeb, 0x28, 0x1e, 0xdc, 0x3e}}
	return a, nil
}

var _tmplSupport_sitesJsonTmpl = "\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x91\xc1\x4e\xc3\x30\x0c\x86\xef\x7b\x0a\xab\xa7\x4d\x8c\x66\xe2\xc0\xa1\x12\xda\x2b\x70\x9f\x07\x6a\x13\xb3\x06\xd2\x26\x6a\x9c\x95\x69\xec\xdd\x51\xd3\xac\x70\x40\xa0\x12\x29\x8a\xf5\xfb\xff\xe5\xcf\xca\x79\x01\x00\x90\x29\xf2\xb2\xd3\x8e\xb5\x6d\xb3\x02\xb2\x47\x43\xa5\x27\x38\x6a\xaf\x19\x6a\x66\xe7\x0b\x21\x0e\x9a\xeb\x50\xe5\xd2\x36\xe2\xc4\xb7\xca\xb8\xeb\x53\x19\x5b\x89\xa6\xf4\x4c\x9d\xf0\xc1\x39\xdb\x31\x29\xaf\x99\x7c\xde\x28\x60\x0b\xb2\x26\xf9\x06\x5c\x13\x18\xed\x19\xec\x0b\x4c\x36\x18\x7d\xd9\x7a\xe4\x48\xfa\x73\x54\xb3\x02\x76\x51\x1e\xce\x79\xaa\xa2\xb1\x2d\x1b\x1a\x48\x4f\x36\x70\xa8\x28\xe5\xa7\x76\x47\x07\x7a\x1f\xfa\xcb\x6d\x31\xf2\x23\x0a\x44\xd1\xf7\x3d\x62\xbe\xda\xa6\x18\x62\x5c\xa7\x2f\x59\xd6\x88\xdb\xe3\xc3\x72\xf7\x84\x61\xb3\xb9\xbb\xdf\xdf\xac\x3e\x7e\xcb\x22\xe6\x15\x89\xef\xf6\x6c\x22\xb8\xac\xff\xa2\xae\xb4\xd1\xc3\x9d\x8b\x7d\xcd\x25\xee\xa3\x56\x64\x07\x08\x31\x73\xbe\xb7\xa1\x55\xd2\xd8\xa0\xe6\x12\x7c\x25\x13\x43\x9a\xfe\x1f\x8a\x56\x4b\x1b\x57\x98\x0b\x31\x05\x11\xf3\x57\x37\x7e\xdf\x0f\x00\xb1\xda\x2f\x2e\x9f\x01\x00\x00\xff\xff\x0a\xa1\x52\x84\xe4\x02\x00\x00"

func tmplSupport_sitesJsonTmplBytes() ([]byte, error) {
	return bindataRead(
		_tmplSupport_sitesJsonTmpl,
		"tmpl/support_sites.json.tmpl",
	)
}

func tmplSupport_sitesJsonTmpl() (*asset, error) {
	bytes, err := tmplSupport_sitesJsonTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "tmpl/support_sites.json.tmpl", size: 740, mode: os.FileMode(0644), modTime: time.Unix(1693627065, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x91, 0x40, 0xab, 0x1, 0xc3, 0xe3, 0x87, 0xfc, 0x7c, 0x86, 0x28, 0x35, 0x36, 0xd0, 0x25, 0xb1, 0xa0, 0xf, 0x22, 0xb9, 0x4d, 0xbb, 0x7c, 0x84, 0x8a, 0x61, 0x1f, 0xcd, 0x3c, 0x0, 0x7e, 0x87}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"tmpl/get_title_and_url.js.tmpl": tmplGet_title_and_urlJsTmpl,
	"tmpl/support_sites.json.tmpl":   tmplSupport_sitesJsonTmpl,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"tmpl": {nil, map[string]*bintree{
		"get_title_and_url.js.tmpl": {tmplGet_title_and_urlJsTmpl, map[string]*bintree{}},
		"support_sites.json.tmpl":   {tmplSupport_sitesJsonTmpl, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
