package lib

import (
	"encoding/json"
	"fmt"
	"regexp"
)

var rangeRegex = regexp.MustCompile(`(?m)^[0-2][0-3]:[0-5][0-9]:[0-5][0-9](?:,(40|[0-3][0-9]|[12][0-9]|[1-9]))?(?:,(40|[0-3][0-9]|[12][0-9]|[1-9])){0,2}$`)

func IsRangeValid(s string) bool {
	return rangeRegex.MatchString(s)
}

var videosRegex = []*regexp.Regexp{}

func IsVideoURLValid(s string) bool {
	for _, r := range videosRegex {
		if r.MatchString(s) {
			return true
		}
	}
	return false
}

type AutoGenerated struct {
	SupportSites []struct {
		Name  string `json:"name"`
		Regex string `json:"regex"`
	} `json:"support_sites"`
}

func LoadSupportSitesRegex(content string) error {
	var data AutoGenerated
	err := json.Unmarshal([]byte(content), &data)
	if err != nil {
		return fmt.Errorf("error unmarshalling the ongoing ringTone: %w", err)
	}

	for _, s := range data.SupportSites {
		videosRegex = append(videosRegex, regexp.MustCompile(s.Regex))
	}
	return nil
}
